---
title: "Applied Statistics -- Exercise 1"
output:
  pdf_document: default
  html_document: default
bibliography: refs.bib
---

*For this first exercise no R-markdown will be required. Later, it will be recommended for you to write down the exercises solutions by R-markdown, especially the solutions to the problems given as home work. In the exam, only R-markdown based presentation will be accepted, unless stated differently.*

\#Preparation

For the theoretical part

-   Read pages 13--21 from @Dekking2010.

For the R-Part

-   Skim through pages 3--18 from @Verzani2014.

-   Install RStudio on your computer. Follow the instructions on the web site <http://www.rstudio.com>

\#Problems

**1.** Use Venn diagrams to show Demorgan's law, i.e.,

a)  $(A \cup B)^\mathrm{C} = A ^\mathrm{C} \cap B ^\mathrm{C}$,

b)  $(A \cap B)^\mathrm{C} = A ^\mathrm{C} \cup B ^\mathrm{C}$.

**2.**

a)  Let $A$ and $B$ be two events in a sample space for which $P(A) = 1/3$, $P(B)=1/6$, and $P(A \cap B) = 1/9$. What is $P(A \cup B)$?

b)  Let $C$ and $D$ be two events for which one knows that $P(C)=0.1$, $P(D)=0.3$, and $P(C \cap D) = 0.05$. What is $P(C \cap D^c)$?

**3.** Consider tossing a fair coin for three times.

a)  Write down the sample space $\Omega$.

Then, write down the set of outcomes and probabilities for the the events

b)  "We throw tails exactly two times",

c)  "We throw heads at least twice,

d)  "Both the first and last throws is heads",

e)  "We get no tails at all".

**4.** Consider tossing a coin repeatedly. Let the probability for heads be $p$, where $0<p<1$, and for tails $1-p$. Now consider that you are interested in the outcome when you'll get the heads exactly for the $third$ time.

(a) What would you consider as the sample space in this case.

(b) Write down the probability that it will take seven tosses to reach the outcome.

**5.** The rule $P(A\cup B)=P(A)+P(B)-P(A\cap B)$ is often useful to compute the probability of the union of the events. What would be the corresponding rule for three events $A,B$, and $C$? It should start with

$P(A\cup B \cup C)=P(A)+P(B)+P(C)-\ldots$

Hint: start from looking at the Venn diagrams to derive the result.

**6.** Use R as you would use a calculator to find numeric aswers to the following expressions

a)  $1 + 2(3+4)$

b)  $4^3+3^{2+1}$

c)  $\sqrt{(4+3)(2+1)}$

d)  $\frac{1+2 \cdot 3^4}{5/6-7}$

e)  $\frac{0.25-0.2}{\sqrt{0.2 \cdot (1-0.2)/100}}$
